version: "3"
services:
  client:
    build:
      context: ./chitchat
    ports:
      - "3000:3000"
    depends_on:
      - server

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
